DROP DATABASE IF EXISTS seleniumDB;
CREATE DATABASE seleniumDB;
USE seleniumDB;
CREATE TABLE CURSOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(35) NOT NULL,
    PROFESOR VARCHAR(50) NOT NULL,
    DIA ENUM('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES'),
    TURNO ENUM('MAÑANA','TARDE','NOCHE')
);
CREATE TABLE ALUMNOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,dadad
    EDAD INT UNSIGNED,
    IDCURSO INT NOT NULL,sdadas
    FOREIGN KEY (IDCURSO) REFERENCES CURSOS(ID)
);
-- ALTER TABLE ALUMNOS
--     ADD CONSTRAINT FK_ALUMNOS_IDCURSO
--     FOREIGN KEY(IDCURSO)
--     REFERENCES CURSOS(ID);

# INSERCION DE CURSOS ---------------------------------------------------------------------------------------

INSERT INTO CURSOS(ID, TITULO, PROFESOR, DIA, TURNO) VALUES(0,'Angular','Carlos Rios','MARTES','TARDE');
INSERT INTO CURSOS(ID, TITULO, PROFESOR, DIA, TURNO) VALUES(0,'PHP', 'Eduardo Gomez','MIERCOLES','MAÑANA');
INSERT INTO CURSOS(ID, TITULO, PROFESOR, DIA, TURNO) VALUES(0,'Photoshop','Lucia Azcuenaga','JUEVES','NOCHE');
INSERT INTO CURSOS(ID, TITULO, PROFESOR, DIA, TURNO) VALUES(0,'C#','Arnold Schmidt','LUNES','NOCHE');
INSERT INTO CURSOS(ID, TITULO, PROFESOR, DIA, TURNO) VALUES(0,'Python','Luciano Castro','VIERNES','MAÑANA');

# INSERCION DE ALUMNOS --------------------------------------------------------------------------------------

INSERT INTO ALUMNOS(ID, NOMBRE, APELLIDO, EDAD, IDCURSO) VALUES (0,'PEPE','MUJICA',44,1);
INSERT INTO ALUMNOS(ID, NOMBRE, APELLIDO, EDAD, IDCURSO) VALUES (0,'ANTONELLA','CIRILLO',32,4);
INSERT INTO ALUMNOS(ID, NOMBRE, APELLIDO, EDAD, IDCURSO) VALUES (0,'DAMIAN','VENEGAS', 29, 5);
INSERT INTO ALUMNOS(ID, NOMBRE, APELLIDO, EDAD, IDCURSO) VALUES (0,'MARIANA', 'MORENO', 17,5);
INSERT INTO ALUMNOS(ID, NOMBRE, APELLIDO, EDAD, IDCURSO) VALUES (0,'CARLA','VALENZUELA', 24, 3);
INSERT INTO ALUMNOS(ID, NOMBRE, APELLIDO, EDAD, IDCURSO) VALUES (0,'TAMARA','ROJAS',22,2);
INSERT INTO ALUMNOS(ID, NOMBRE, APELLIDO, EDAD, IDCURSO) VALUES (0,'VIVIANA','ROJAS',22,2);

SELECT * FROM ALUMNOS
